arguments:
  app_name: Radarr
  altname: radarr
  pro_only: false
  logo_path: radarr.png
  group: media
  details:
    docs: https://wiki.servarr.com/Radarr
    github: https://github.com/Radarr/Radarr
    homepage: https://radarr.video/
    mediaease_docs: https://mediaease.github.io/docs/software/official/radarr
  multi_user: true
  service_directives:
    - Type=simple
    - Environment=TMPDIR=/home/%i/tmp/$app_name
    - ExecStartPre=-/bin/mkdir -p /home/%i/tmp/$app_name
    - ExecStart=/opt/%i/$app_name/Radarr -nobrowser -data=/home/%i/.config/$app_name -config=/home/%i/.config/$app_name/config.xml
    - TimeoutStopSec=20
  files:
    - service: /etc/systemd/system/$app_name@.service
    - config: /home/%i/.config/$app_name/config.xml
    - proxy: /etc/caddy/softwares/%i.$app_name.caddy
    - database: /home/%i/.config/$app_name/$app_name.db
  paths:
    - backup: /home/%i/.mediaease/backups/$app_name
    - data: /home/%i/.config/$app_name
    - install: /opt/%i/$app_name
  autogen:
    - apikey
    - ssl_port
    - default_port
  ui_options:
    - subdomain: true
    - branches: [main, beta]
  release_name: linux-core-x64.tar.gz
  executable_files: [/opt/%i/$app_name/Radarr, /opt/%i/$app_name/Sonarr]
