arguments:
  app_name: Filebrowser
  altname: filebrowser
  description: filebrowser_description
  pro_only: false
  logo_path: filebrowser.png
  group: full
  details:
    docs: https://filebrowser.org/
    github: https://github.com/filebrowser/filebrowser
    homepage: https://filebrowser.org/
    mediaease_docs: https://mediaease.github.io/docs/software/official/filebrowser
  multi_user: true
  ports:
    - default: [12001-13999]
    - ssl: [35001-35999]
  service_directives:
    - Type=simple
    - ExecStart=/usr/local/bin/$app_name -d /home/%i/.config/$app_name/$app_name.db
    - ExecStop=/usr/bin/killall -w -s 9 /usr/local/bin/$app_name
    - Restart=on-failure
    - TimeoutStopSec=300
  files:
    - service: /etc/systemd/system/$app_name@.service
    - config: /home/%i/.config/$app_name/$app_name.db
    - proxy: /etc/caddy/softwares/%i.$app_name.caddy
  paths:
    - backup: /home/%i/.mediaease/backups/$app_name
    - data: /home/%i/.config/$app_name
    - install: /opt/%i/$app_name
  autogen:
    - apikey
    - ssl_port
    - default_port
