#!/bin/bash

# file.sh - File manipulation functions for MediaEase

function file::fine_tune_permissions() {
    local path="$1"
    local user="$2"
    local group="$3"
    local dir_permissions="$4"
    local file_permissions="$5"
    logger::log "info" "$(i18n::translate "tuning_permissions" "$path")"
    if [ ! -e "$path" ]; then
        logger::log "error" "$(i18n::translate "path_not_found" "$path")"
        return 1
    fi
    chown -R "$user:$group" "$path"
    find "$path" -type d -exec chmod "$dir_permissions" {} +
    find "$path" -type f -exec chmod "$file_permissions" {} +
    logger::log "success" "$(i18n::translate "permissions_tuned" "$path")"
}

function file::git_clone_if_not_exists() {
    local repo_url="$1"
    local target_dir="$2"

    if [ ! -d "$target_dir" ]; then
        if logger::do "git clone $repo_url $target_dir"; then
            logger::log "info" "$(i18n::translate "repository_cloned" "$repo_url")"
        else
            logger::log "error" "$(i18n::translate "repository_not_cloned" "$repo_url")"
        fi
    else
        logger::log "info" "$(i18n::translate "repository_exists" "$repo_url")"
    fi
}

function file::load_locale_file() {
    local lang="$1"
    local locale_setting
    declare -A system_lang=(
        ["en"]="en_US.UTF-8"
        ["fr"]="fr_FR.UTF-8"
    )
    if [[ -z "${system_lang[$lang]}" ]]; then
        logger::log "error" "$(i18n::translate "unsupported_languages" "${lang}")"
        exit 1
    fi
    locale_setting="${system_lang[$lang]}"
    echo "LANGUAGE=\"$locale_setting\"" >/etc/default/locale
    echo "LC_ALL=\"$locale_setting\"" >>/etc/default/locale
    echo "$locale_setting UTF-8" >/etc/locale.gen
    logger::do "locale-gen $locale_setting"
    if [[ -z "$MEDIAEASE_HOME" ]]; then
        MEDIAEASE_HOME="$(dirname "$(readlink -f "$0")")"
    fi
    MEDIAEASE_HOME="${MEDIAEASE_HOME%/}"
    local locale_file="${MEDIAEASE_HOME}/scripts/translations/locales_${lang}.yaml"
    if [[ -f "$locale_file" ]]; then
        printf "%s\n" "$locale_file"
        export LANG="$locale_setting"
        export LC_ALL="$locale_setting"
        export LANGUAGE="$locale_setting"
        export MEDIAEASE_LOCALE_FILE="$locale_file"
    else
        logger::log "warning" "$(i18n::translate "locale_file_not_found" "$locale_file")"
    fi
}

function file::environment::variable::get() {
    local var_name="$1"
    if [[ -n "${!var_name}" ]]; then
        echo "${!var_name}"
    else
        logger::log "error" "$(i18n::translate "env_var_not_found" "$var_name")"
    fi
}
