arguments:
  app_name: Bazarr
  altname: bazarr
  pro_only: false
  logo_path: bazarr.png
  group: media
  details:
    docs: https://wiki.bazarr.media/
    github: https://github.com/morpheus65535/bazarr
    homepage: https://bazarr.media/
    mediaease_docs: https://mediaease.github.io/docs/software/official/bazarr
  multi_user: true
  service_directives:
    - Type=simple
    - Environment=TMPDIR=/home/%i/tmp/$app_name
    - ExecStartPre=-/bin/mkdir -p /home/%i/tmp/$app_name
    - ExecStartPre=/bin/sleep 30
    - ExecStart=/usr/bin/python3 /opt/%i/$app_name/bazarr.py --config "/home/%i/.config/$app_name"
    - UMask=0002
    - Restart=on-failure
    - RestartSec=5
    - KillSignal=SIGINT
    - TimeoutStopSec=20
  files:
    - service: /etc/systemd/system/$app_name@.service
    - config: /home/%i/.config/$app_name/config.ini
    - proxy: /etc/caddy/softwares/%i.$app_name.caddy
  paths:
    - backup: /home/%i/.mediaease/backups/$app_name
    - data: /home/%i/.config/$app_name
    - install: /opt/%i/$app_name
  autogen:
    - apikey
    - ssl_port
    - default_port
