arguments:
  app_name: FlareSolverr
  altname: flaresolverr
  pro_only: false
  logo_path: flaresolverr.png
  group: proxy
  details:
    github: https://github.com/FlareSolverr/FlareSolverr
    mediaease_docs: https://mediaease.github.io/docs/software/official/flaresolverr
  multi_user: true
  service_directives:
    - Type=simple
    - Environment="LOG_LEVEL=info"
    - Environment="CAPTCHA_SOLVER=none"
    - Environment="LANG=en_US"
    - Environment="PORT={{default_port}}"
    - ExecStartPre=-/bin/mkdir -p /home/%i/tmp/$app_name
    - WorkingDirectory=/opt/%i/$app_name
    - ExecStart=/opt/%i/$app_name/$app_name
    - TimeoutStopSec=30
    - SyslogIdentifier=$app_name for %i
    - Restart=always
    - RestartSec=5
  files:
    - service: /etc/systemd/system/$app_name@.service
    - proxy: /etc/caddy/softwares/%i.$app_name.caddy
  paths:
    - backup: /home/%i/.mediaease/backups/$app_name
    - install: /opt/%i/$app_name
  autogen:
    - apikey
    - ssl_port
    - default_port
  ui_options:
    - subdomain: true
