#!/usr/bin/env bash
# @file software/official/flaresolverr/flaresolverr.sh
# @version 1.1.15
# @project MediaEase
# @description FlareSolverr handler
# @author Thomas Chauveau (tomcdj71)
# @author_contact thomas.chauveau.pro@gmail.com
# @license BSD-3 Clause (Included in LICENSE)
# @copyright Copyright (C) 2025, MediaEase

# @function zen::software::flaresolverr::add
# @description Adds a FlareSolverr for a user, including downloading, configuring, and starting the service.
# @global software_config_file Path to the software's configuration file.
# @global user An associative array containing user-specific information.
# @note Disables SC2154 because the variable is defined in the main script.
# shellcheck disable=SC2154
zen::software::flaresolverr::add() {
    # grab the correct release
    zen::git::get_release "/opt/${user[username]}/$app_name" "${config[github]}" "${software_options[is_prerelease]}" "${config[release_name]}"
    # configure the app. This will also generate the proxy file
    zen::software::flaresolverr::config "${software_options[is_prerelease]}"
    # generate the service file, this will also start it
    zen::service::generate "$app_name" "${config[config_file]}"
    # create a backup file
    zen::software::backup::create "$app_name" "${config[config_file]}"
}

################################################################################
# @function zen::software::flaresolverr::config
# @description Configures FlareSolverr for a user, including setting up configuration files and proxy settings.
# @arg $1 string Indicates whether to use a prerelease version of FlareSolverr.
# @global user An associative array containing user-specific information.
# @example
#   # the following disables pre-release (develop):
#   zen::software::flaresolverr::config "false"
#   # the following enables pre-release (nightly):
#   zen::software::flaresolverr::config "true"
zen::software::flaresolverr::config() {
    local is_prerelease="$1"
    declare -g url_base
    mflibs::shell::text::white "$(zen::i18n::translate "messages.software.configure" "$app_name")"
    zen::software::autogen
    echo "3.11" >"/opt/${user[username]}/$app_name/.python-version"
    zen::workspace::venv::create "/opt/${user[username]}/$app_name" "${user[username]}" "true"
    url_base="/${user[username]}/${app_name}"
    mkdir -p "/home/${user[username]}/.config/${app_name}"
    # generate the proxy configuration
    zen::permission::read_exec "/home/${user[username]}/.config/${app_name}" "${user[username]}"
    zen::permission::read_exec "/opt/${user[username]}/${app_name}" "${user[username]}"
    zen::permission::user_exec "/opt/${user[username]}/$app_name/flaresolverr" "${user[username]}"
    zen::proxy::generate "$app_name" "$default_port" "$url_base"
    mflibs::shell::text::green "$(zen::i18n::translate "success.software.configure" "$app_name")"
}

# @function zen::software::flaresolverr::update
# @description Updates FlareSolverr for a user, including stopping the service, downloading the latest release, and restarting.
# @global user An associative array containing user-specific information.
# @global software_config_file Path to the software's configuration file.
zen::software::flaresolverr::update() {
    local service_name
    is_multi=$(zen::software::get_config_key_value "$software_config_file" '.arguments.multi_user')
    [ "$is_multi" == "true" ] && service_name="$app_name@${user[username]}.service" || service_name="$app_name.service"
    zen::service::manage "stop" "$service_name"
    rm -rf "/opt/${user[username]}/$app_name"
    is_prerelease="false"
    [[ "$software_branch" == "beta" ]] && is_prerelease="true"
    # grab the correct release
    zen::git::get_release "/opt/${user[username]}/$app_name" "${config[github]}" "${software_options[is_prerelease]}" "${config[config_file]}"
    zen::service::manage "start" "$service_name"
}

# @function zen::software::flaresolverr::remove
# @description Removes FlareSolverr for a user, including disabling and deleting the service and cleaning up files.
# @global user An associative array containing user-specific information.
zen::software::flaresolverr::remove() {
    local service_name
    is_multi=$(zen::software::get_config_key_value "$software_config_file" '.arguments.multi_user')
    [ "$is_multi" == "true" ] && service_name="$app_name@${user[username]}.service" || service_name="$app_name.service"

    zen::service::manage "disable" "$service_name"
    rm -f "$service_file"
    zen::proxy::remove "$app_name" "${user[username]}"
    rm -rf /opt/"${user[username]}"/"$app_name"
    rm -rf /home/"${user[username]}"/.config/"$app_name"
    rm -rf /home/"${user[username]}"/tmp/"$app_name"
}

# @function zen::software::flaresolverr::backup
# @description Creates a backup for FlareSolverr settings for a user.
# @note This function is currently a placeholder and needs implementation.
zen::software::flaresolverr::backup() {
    local username="$1"
    local app_name="$2"
}

# @function zen::software::flaresolverr::reset
# @description Resets FlareSolverr settings for a user.
# @note This function is currently a placeholder and needs implementation.
zen::software::flaresolverr::reset() {
    local username="$1"
    local app_name="$2"
}

# @function zen::software::flaresolverr::reinstall
# @description Reinstalls FlareSolverr for a user.
# @note This function is currently a placeholder and needs implementation.
zen::software::flaresolverr::reinstall() {
    local username="$1"
    local app_name="$2"
}
