arguments:
  app_name: rTorrent
  altname: rtorrent
  note: rtorrent_note
  pro_only: false
  logo_path: rtorrent.png
  precompiled: true
  precompiled_description: rtorrent_precompiled_description
  multi_user: true
  group: download
  details:
    github: https://github.com/rakshasa/rtorrent
    homepage: http://rakshasa.github.io/rtorrent/
    mediaease_docs: https://mediaease.github.io/docs/software/official/rtorrent
  service_directives:
    - Type=forking
    - KillMode=none
    - ExecStartPre=-/bin/rm -f /home/%i/download-clients/.sessions/$app_name.lock
    - ExecStart=/usr/bin/screen -d -m -fa -S $app_name /usr/bin/$app_name
    - ExecStop=/usr/bin/screen -X -S $app_name quit
    - WorkingDirectory=/home/%i/
  files:
    - service: /etc/systemd/system/$app_name@.service
    - config: /home/%i/.$app_name.rc
    - proxy: /etc/caddy/softwares/%i.scgi.caddy
  paths:
    - backup: /home/%i/.mediaease/backups/$app_name
    - data: /home/%i/download-clients/$app_name
  autogen:
    - port_range
  versions:
    - "0.9.6"
    - "0.9.7"
    - "0.9.8"
