arguments:
  app_name: ruTorrent
  altname: rutorrent
  note: rutorrent_note
  pro_only: false
  multi_user: false
  logo_path: rutorrent.png
  group: automation
  parent_service: rTorrent
  details:
    github: https://github.com/Novik/ruTorrent
    homepage: https://rutorrent.video/
    mediaease_docs: https://mediaease.github.io/docs/software/official/rutorrent
  files:
    - config: /srv/$app_name/config.php
    - proxy: /etc/caddy/softwares/$app_name.caddy
  ports:
    - default: [80-80]
    - ssl: [443-443]
  paths:
    - backup: /home/%i/.mediaease/backups/$app_name
    - data: /srv/$app_name
  skip_requirements_check: true
