arguments:
  app_name: Autobrr
  altname: autobrr
  description: autobrr_description
  pro_only: false
  logo_path: autobrr.png
  group: automation
  details:
    docs: https://autobrr.com/introduction
    github: https://github.com/autobrr/autobrr
    homepage: https://autobrr.com
    mediaease_docs: https://mediaease.github.io/docs/software/official/autobrr
  multi_user: true
  ports:
    - default: [12001-13999]
    - ssl: [35001-35999]
  service_directives:
    - Type=simple
    - Environment=TMPDIR=/home/%i/tmp/$app_name
    - ExecStartPre=-/bin/mkdir -p /home/%i/tmp/$app_name
    - ExecStartPre=/bin/sleep 30
    - ExecStart=/usr/local/bin/$app_name --config=/home/%i/.config/$app_name
  files:
    - service: /etc/systemd/system/$app_name@.service
    - config: /home/%i/.config/$app_name/config.ini
    - proxy: /etc/caddy/softwares/%i.$app_name.caddy
  paths:
    - backup: /home/%i/.mediaease/backups/$app_name
    - data: /home/%i/.config/$app_name
    - install: /opt/%i/$app_name
  autogen:
    - apikey
    - ssl_port
    - default_port
