global:
  scrape_interval: 30s
  evaluation_interval: 15s 
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9902

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"


scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9901"]
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['localhost:9903']
  - job_name: 'smartctl'
    static_configs:
      - targets: ['localhost:9904']
  - job_name: 'blackbox-service-status'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - /opt/grafana/tools/configs/blackbox/blackbox.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 0.0.0.0:9905
