arguments:
  app_name: Sonarr4K
  altname: sonarr4k
  pro_only: false
  logo_path: sonarr4k.png
  group: media
  details:
    docs: https://wiki.servarr.com/Sonarr
    github: https://github.com/Sonarr/Sonarr
    homepage: https://sonarr.tv/
    mediaease_docs: https://mediaease.github.io/docs/software/official/sonarr
  multi_user: true
  service_directives:
    - Type=simple
    - Environment=TMPDIR=/home/%i/tmp/$app_name
    - ExecStartPre=-/bin/mkdir -p /home/%i/tmp/$app_name
    - ExecStart=/opt/%i/$app_name/Sonarr -nobrowser -data=/home/%i/.config/$app_name -config=/home/%i/.config/$app_name/config.xml
    - TimeoutStopSec=20
  files:
    - service: /etc/systemd/system/$app_name@.service
    - config: /home/%i/.config/$app_name/config.xml
    - proxy: /etc/caddy/softwares/%i.$app_name.caddy
  paths:
    - backup: /home/%i/.mediaease/backups/$app_name
    - data: /home/%i/.config/$app_name
    - install: /opt/%i/$app_name/software/official/prowlarr/
  autogen:
    - apikey
    - ssl_port
    - default_port
  ui_options:
    - subdomain: true
    - branches: [main, beta]
