{
 "title": "testounet",
 "description": "Monitor Linux host (VM, Server, OS), your personal machines with preconfigured beautiful dashboard.",
 "tags": [
  "linux",
  "mediaease",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(node_uname_info{instance=~\"$instance(.*)\"},instance)"
    }
   },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "query_result(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\"} or windows_net_bytes_received_total{job=\"$job\",instance=\"$instance\"})"
    }
   },
   { "name": "interval", "label": "interval", "query": "1m,5m,15m,1h" },
   {
    "name": "cpus",
    "label": "cpus",
    "query": {
     "query": "label_values(node_cpu_seconds_total{job=~\"$job\"},cpu)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "vpc",
    "label": "Vpc",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},vpcid)"
    }
   },
   {
    "name": "subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\", vpc=~\"$vpc\"},subnet)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\",job=\"$job\"} - node_boot_time_seconds{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Domain",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{domainname}}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\",job=\"$job\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Network Traffic In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"eth0\", instance=~\"localhost:2020\"}"
    }
   ]
  },
  {
   "title": "Network Traffic Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"eth0\", instance=~\"localhost:2020\"}"
    }
   ]
  },
  {
   "title": "Network Traffic - Wireguard",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance:\", device=~\"wg0\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Rx"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:$port\", device=~\"wg0\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Tx"
    }
   ]
  },
  {
   "title": "Network Traffic - Lan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\", device=~\"eth0\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Rx"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\", device=~\"eth0\",job=~\"$job\"}[5m])",
     "legendFormat": "{{device}} - Tx"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU iowait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"iowait\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[$__interval])) by (mode))  / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "(sum(rate(node_cpu_seconds_total{instance=~\"$instance\",mode!=\"idle\"}[$__interval])))  / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by(instance) (irate(windows_cpu_time_total{instance=\"$instance\",job=\"$job\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_load1{instance=~\"$instance\"}) / max(count(node_cpu_seconds_total{instance=~\"$instance\", mode=~\"system\"}))",
     "legendFormat": "1m"
    },
    {
     "expr": "max(node_load5{instance=~\"$instance\"}) / max(count(node_cpu_seconds_total{instance=~\"$instance\", mode=~\"system\"}))",
     "legendFormat": "5m"
    },
    {
     "expr": "max(node_load15{instance=~\"$instance\"}) / max(count(node_cpu_seconds_total{instance=~\"$instance\", mode=~\"system\"}))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp0\"}",
     "legendFormat": "0"
    },
    {
     "expr": "node_hwmon_temp_celsius{sensor=\"temp1\"}",
     "legendFormat": "1"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Running processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_running{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_processes{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"} + node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "Buffers/Cached"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$instance\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$instance\",job=\"$job\"} )) * 100"
    }
   ]
  },
  { "title": "FileSystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Disk Space Used (EXT4/XFS/BTRFS)",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext4|xfs|btrfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~'$instance',fstype=~\"ext4|xfs|btrfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'$instance',fstype=~\"ext4|xfs|btrfs\"} / node_filesystem_size_bytes{instance=~'$instance',fstype=~\"ext4|xfs|btrfs\"})"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_healthy{instance=~\"$instance\"})-sum(smartmon_device_smart_healthy{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Errors All Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum( smartmon_reallocate_nand_blk_cnt_raw_value ) +\nsum( smartmon_reallocated_sector_ct_raw_value ) +\nsum( smartmon_reallocated_event_count_raw_value ) +\nsum( smartmon_raw_read_error_rate_raw_value ) +\nsum( smartmon_current_pending_sector_raw_value ) +\nsum( smartmon_offline_uncorrectable_raw_value ) +\nsum( smartmon_udma_crc_error_count_raw_value ) +\nsum( smartmon_seek_error_rate_raw_value ) +\nsum( smartmon_spin_retry_count_raw_value ) +\nsum( smartmon_multi_zone_error_rate_raw_value )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "S.M.A.R.T Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  { "title": "Network $network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }, "repeat": "network" },
  {
   "title": "(IN) $network",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\",device=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(windows_net_bytes_received_total{job=\"$job\",instance=\"$instance\",nic=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(irate(node_network_receive_bytes_total{job=\"$job\",instance=\"$instance\",device=\"$network\"}[$__rate_interval])*8) or (irate(windows_net_bytes_received_total{job=\"$job\",instance=\"$instance\",nic=\"$network\"}[$__rate_interval])*8)",
     "legendFormat": "receive"
    },
    {
     "expr": "(irate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$instance\",device=\"$network\"}[$__rate_interval])*8) or (irate(windows_net_bytes_sent_total{job=\"$job\",instance=\"$instance\",nic=\"$network\"}[$__rate_interval])*8)",
     "legendFormat": "transmit"
    },
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "(OUT) $network",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$instance\",device=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(windows_net_bytes_sent_total{job=\"$job\",instance=\"$instance\",nic=\"$network\"}[$__rate_interval])*8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}