name: Update Submodule

on:
  release:
    types: [published, created]

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get the latest release details
        id: get_latest_release
        uses: actions/github-script@v3
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return {
              id: release.data.id,
              tag_name: release.data.tag_name,
              prerelease: release.data.prerelease,
              body: release.data.body
            };
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch for Scripts
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MEDIAEASE_ACCESS_TOKEN }}
          repository: MediaEase/MediaEase
          event-type: zen-release
          client-payload: |
            {
              "submodule": "zen",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "zen_version": "${{ steps.get_latest_release.outputs.tag_name }}",
              "release_type": "${{ steps.get_latest_release.outputs.prerelease ? 'prerelease' : 'release' }}",
              "zen_release_notes": "${{ steps.get_latest_release.outputs.body }}"
            }
